name: Run Wishxporter Lite Mode
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '>=12.14.1'
    - name: Install dependencies
      run: npm ci
    - name: Install wishxporter
      run: npm install -g wishxporter
    - name: Run wishxporter
      run: wishxporter --lite
      env:
        AUTHKEY_URL: ${{ secrets.AUTHKEY_URL }}
